apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: carpool-web
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: python
    namespace: default
  package:
    functionName: app.main
    packageref:
      name: cp-web-pkg
      namespace: default
      resourceversion: "10530"
  resources: {}
  secrets: null

