apiVersion: fission.io/v1
kind: Package
metadata:
  name: cp-web-pkg
  namespace: default
spec:
  deployment:
    url: archive://cp-web-pkg-zip
  buildcmd: "build"
  environment:
    name: python
    namespace: default
status:
  buildstatus: succeeded

---
kind: ArchiveUploadSpec
name: cp-web-pkg-zip
include:
  - "04_carpool_dashboard/*"
